version: '3'

services:
  app:
    container_name: desafio-agendamento-churrasco-dev
    image: desafio-agendamento-churrasco-dev
    build:
      context: .
      target: development
      args:
       - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - ./src:/app/src
    stdin_open: true
    ports:
      - 3000:3000
